default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.24.2
  hooks:
    - id: gitleaks

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.2.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: []

- repo: local
  hooks:
    - id: ruff-format
      name: ruff-format
      entry: uv run ruff check --fix
      language: system
      pass_filenames: false
      always_run: true
    - id: ruff-check
      name: ruff-check
      entry: uv run ruff check
      language: system
      pass_filenames: false
      always_run: true
    - id: pytest
      name: pytest
      entry: uv run pytest --cov=src
      language: system
      pass_filenames: false
      always_run: true

